quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/

# Disable Hibernate auto DDL - schema will be managed by Flyway
quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

# Enable Flyway migrations on startup
quarkus.flyway.migrate-at-start=true

quarkus.application.name=eyebrow-api
quarkus.application.version=1.0.0

%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=http://localhost:5173
